<Project Sdk="Meziantou.NET.Sdk.Test">

  <PropertyGroup>
    <!-- The tests share the console, so they must not run in parallel -->
    <XunitParallelizationMode>None</XunitParallelizationMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Framework.InlineSnapshotTesting" Version="3.3.37" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Meziantou.GitHubActionsTracing\Meziantou.GitHubActionsTracing.csproj" />
    <EmbeddedResource Include="TestData\**\*.zip" />
  </ItemGroup>

</Project>
